# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.154.2+26.2

# Mod Properties
mod_version_prefix=0.5.4.3
mod_version=
mod_version_suffix=
maven_group=cn.LPCTools
archives_base_name=LPCTools

# Required malilib version
# https://github.com/sakura-ryoko/malilib/releases
# https://modrinth.com/mod/malilib
malilib_version = 0.29.3
conditionalmixin_version = 0.6.4

# minihud version
# https://github.com/sakura-ryoko/minihud/releases
# https://modrinth.com/mod/minihud
minihud_version = 0.40.3

# litematica version
# https://github.com/sakura-ryoko/litematica/releases
# https://modrinth.com/mod/litematica
litematica_version = 0.28.3

# tweakeroo version
# https://github.com/sakura-ryoko/tweakeroo/releases
# https://modrinth.com/mod/tweakeroo
tweakeroo_version = 0.29.2

# placeholder-api version
# https://modrinth.com/mod/placeholder-api
placeholder_api_version = 3.1.0-beta.1+26.2

# mod_menu version
# https://github.com/TerraformersMC/ModMenu/releases
# https://modrinth.com/mod/modmenu
mod_menu_version = 20.0.0-beta.4

# spark version
# https://modrinth.com/mod/spark
spark_version = 1.10.173-fabric

# fabric permission api version
# https://modrinth.com/mod/fabric-permissions-api
# fabric_permissions_api_version = 0.6.1

# sodium version
# https://modrinth.com/mod/sodium
sodium_version = mc26.2-0.9.0-fabric

# iris version
# https://modrinth.com/mod/iris
iris_version = 1.11.1+26.2-fabric

# immediatelyfast version
# https://modrinth.com/mod/immediatelyfast
immediatelyfast_version = 1.16.1+26.2-fabric
reflect_version=1.6.1+curseforge

# viafabricplus version
# https://modrinth.com/mod/viafabricplus
viafabricplus_version = 4.6.1

# xaero world map version
# https://modrinth.com/mod/xaeros-world-map
xaero_world_map_version = fabric-26.2-1.41.3

# xaero minimap version
# https://modrinth.com/mod/xaeros-minimap
xaero_minimap_version = fabric-26.2-26.1.3
